# Generated by Django 3.1.7 on 2021-03-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='amount',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='expense',
            name='text',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
